### ISSUE TITLE
Import MoneyData

### ISSUE THREAD

**Issue by dvilcode** [onepub-dev/money.dart#64]
Hello,
Currently I'm using Encoders and Decoders for custom objects on Money class.
On the current version (3.1.2) I noticed there was missing the import for MoneyData
that is necessary for those abstract classes MoneyEncoder and MoneyDecoder.

I placed the import for the class MoneyData dierctly (same like in the test file), but I got this message by the dart analyzer:
![Screenshot 2022-02-09 042546](https://user-images.githubusercontent.com/48808625/153167087-446827ca-7bb2-4a69-8b59-21506818034b.png)

Maybe there are missing the right import for this class (MoneyData)?

Thank you!
Regards.

**Comment by bsutton** [comment]
The problem will be that the Money class isn't exporting the MoneyData
class.

I can add it into the barrel file.

Can I ask why you are using the encoders?
In most scenarios they are simply not required.

I've published 3.1.3-beta-1 with the exported file.

S. Brett Sutton
OnePub.dev
The private repository service for Dart Developers.

**Comment by dvilcode** [comment]
Thank you!
Sure, I'm using a class for kind of serialization with json_serializable and Money2, storing the data with this class's structure.

**Comment by bsutton** [comment]
released in the latest version.
