### ISSUE TITLE
tryParse throws when monetary amount is empty

### ISSUE THREAD

**Issue by LewisHolliday** [onepub-dev/money.dart#68]
Example
```dart
Money.tryParse('', code: 'USD') //throws
```
Instead of returning null, an error is thrown.

**Comment by bsutton** [comment]
Lewis,
I've just published 3.1.4 which includes your PR as well as fixes for Money.parse not throwing a MoneyParseException.

Greatly appreciate the PR.

I'm wondering if I could ask a favour.
I've just founded a company, OnePub and we have released our beta at onepub.dev.
It's a private package repository for dart.
I'm looking for beta testers and some feedback on the service.
The service is free during beta and anyone publishing a package during the beta receives a lifetime free subscription.

Brett
