### ISSUE TITLE
findByCode miss the match code

### ISSUE THREAD

**Issue by kopianan** [onepub-dev/money.dart#72]
OLD : 
<img width="967" alt="image" src="https://user-images.githubusercontent.com/34189066/192683566-cd966cfb-71a5-4602-a097-dce7e9d8e57a.png">

NEW : 
<img width="523" alt="image" src="https://user-images.githubusercontent.com/34189066/192683606-cfcd5a7c-8ea3-4b87-a704-7a9a80e8e5a3.png">

I create PR Here : 

https://github.com/onepub-dev/money.dart/pull/71

**Comment by bsutton** [comment]
Resolved.

Searching for a non-existing code such as USDT will not return a partial match such as USD.
