### ISSUE TITLE
please add minimum decimal support in pattern

### ISSUE THREAD

**Issue by anggaaryas** [onepub-dev/money.dart#73]
for example: #,##0.00########

it should have minimum 2 digit decimal / 2 decimal padding. Currently it doesnt support.

```
   var curr = Currency.create('USD', 8, pattern: "S #,###.########", symbol: '\$');
    print(Money.fromFixedWithCurrency(Fixed.parse('1000000000.1'), curr).toString());
```

**Comment by hyeonjoonpark** [comment]
hi i have solution

**Comment by hyeonjoonpark** [comment]
f u

**Comment by anggaaryas** [comment]
for example: #.###.00###

100.90 => 100.90
100.9876 => 100.9876
100.9 => 100.90 (because the minimum decimal is 2 digit)
100 => 100.00 (because the minimum decimal is 2 digit)

**Comment by bsutton** [comment]
So what are you observing?

What is the scale of the no. that you are passing.

**Comment by bsutton** [comment]
Your code and your example don't seem to line up so a worked example with the expected output would be helpful such as a unit test
