### ISSUE TITLE
fromNumWithCurrency

### ISSUE THREAD

**Issue by flutter-painter** [onepub-dev/money.dart#77]
Why include Money.fromNumWithCurrency if it is recommended not to use float/double ?
Why not prefer  Money.parse to encourage users to stick to int / String or Money types ?

**Comment by bsutton** [comment]
It's about usability.
Whether we recommend using doubles or not,at some point someone is going to have one.
If we removed the fromNum then the user would first have to convert the num to  a string and then pass it to Money.
The user is less likely to format the string correctly and therefore cause rounding problems.

**Comment by flutter-painter** [comment]
Thank you for your clear answer,
Running below test I understand that using Money here prevents users from double rounding error as well as format mistakes.
Cheers !


```dart
test('fromNum rocks!', () {
    const x = 4.35;
    const y = x * 100;
    final dd = Money.fromNum(y, code: 'USD');
    expect(dd.amount, 435.00);
    expect(dd.minorUnits, 43500);
  });
```
