### ISSUE TITLE
Money.operator== incompatible with dart_mappable, causing exceptions in copyWith

### ISSUE THREAD

**Issue by karelklic** [onepub-dev/money.dart#85]
Hello and thank you for developing this handy package.

When a `Money? money` variable is put into a class that has a [copyWith](https://pub.dev/documentation/dart_mappable/latest/topics/Copy-With-topic.html) method generated by [dart_mappable](https://pub.dev/packages/dart_mappable), all `copyWith` calls result in a runtime type error.

It's caused by the `Money.operator==` having a `covariant Money other` argument instead of a more generic `Object other`.

The auto-generated `copyWith` method needs to allow setting the `Money? money` variable to null, but also allow the caller to keep it intact by not providing any value. This is implemented by using a special token that indicates that the object should not be changed: `copyWith(Object? money = $none)`. The parameter is then compared with the `$none` token inside the method, resulting in the type error caused by the `covariant Money` check.

The easiest solution would be to change `Money.operator==` to return `false` on incompatible type instead of throwing an exception.
The topic was discussed in issue #40, which resulted in using the covariant.

Could you please consider it again, given this use case?

([freezed](https://pub.dev/packages/freezed) users will probably suffer from the same issue because `copyWith` there uses a similar technique. )

**Comment by bsutton** [comment]
If you would like to submit a pr I will merge it.
